
# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

#   backend:
#     build: ./backend
#     ports:
#       - "4000:4000"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_USER=postgres
#       - DB_PASSWORD=2009
#       - DB_DATABASE=registro_ponto
#     depends_on:
#       - db

#   db:
#     image: postgres:14
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 2009
#       POSTGRES_DB: registro_ponto
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   pgdata:
